version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile  # This is assuming the backend Dockerfile is in the root directory
    ports:
      - "8082:9090"
    depends_on:
      - mysql

  frontend:
    build:
      context: ./frontend/Task-Management-System  # Pointing to the correct directory
      dockerfile: Dockerfile  # Ensure this is the correct path to the Dockerfile
    ports:
      - "3001:80"
    depends_on:
      - backend

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: bindu
    ports:
      - "3308:3306"
