version: "3.8"

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: bindu
      MYSQL_DATABASE: task_management
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: bindu892/backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:9090"
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    image: bindu892/frontend:latest
    build:
      context: ./frontend/Task-Management-System
      dockerfile: Dockerfile
    ports:
      - "3002:80"
    depends_on:
      - backend
