version: "3.8"

services:
  backend:
    image: bindu892/backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:9090"
    depends_on:
      - mysql

  frontend:
    image: bindu892/frontend:latest
    build:
      context: ./frontend/Task-Management-System
      dockerfile: Dockerfile
    ports:
      - "3002:80"
    depends_on:
      - backend

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: bindu
      MYSQL_DATABASE: task_management
    ports:
      - "3307:3306"
